[package]
name = "intcode-rs"
version = "0.1.0"
authors = ["Kyle Silver <***REMOVED***>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"